version: '3.9'

services:
 frontend:
   container_name: frontend
   restart: always
   build: frontend/
   ports:
     - "3000:3000"
   volumes:
     - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

 backend:
   container_name: backend
   restart: always
   build: backend/
   ports:
     - "8000:8000"
  #  depends_on:
  #    - postgres
   networks:
     - db_network

  # postgres:
  #     image: postgres
  #     container_name: postgres
  #     environment:
  #       - POSTGRES_USER=${POSTGRES_USER}
  #       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     ports:
  #       - "5432:5432"
  #     networks:
  #       - db_network
  #     command: [ "postgres", "-c", "log_destination=stderr", "-c", "logging_collector=on", "-c", "log_directory=/var/log/postgresql" ]

networks:
  db_network:
    driver: bridge

# volumes:
#   postgres_data: